# Generated by Django 4.2.8 on 2023-12-28 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Cahppa',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Type_Style', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cahppa',
            fields=[
                ('name', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('colur', models.CharField(max_length=100)),
                ('provider', models.CharField(max_length=200)),
                ('id_Type_Style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Index.model_cahppa')),
            ],
        ),
    ]
